[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
list_db = True
dev_mode = reload,qweb,werkzeug,xml
log_level = info
log_handler = :INFO
workers = 0
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
limit_request = 65536
smtp_server = mailpit
smtp_port = 1025
smtp_ssl = False
email_from = odoo@localhost
